<?xml version="1.0" encoding="utf-8"?><Database Name="usersDB" Class="Exp15_DCDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=DESKTOP-BJ8LKKA\SQLEXPRESS;Initial Catalog=usersDB;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="usersDBConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.BasicUserTabel" Member="BasicUserTabels">
    <Type Name="BasicUserTabel">
      <Column Name="u_name" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="u_email" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="u_password" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
    </Type>
  </Table>
</Database>